packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": ^22.10.7
  "@types/react": ^19.0.7
  "@types/react-dom": ^19.0.3
  eslint: ^9.18.0
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.7.3
